name: qrsac_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - glew=2.2.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglu=9.0.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - python=3.10.16
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - box2d-py==2.3.5
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - cloudpickle==3.1.0
      - cython==3.0.11
      - fasteners==0.19
      - filelock==3.16.1
      - fsspec==2024.10.0
      - glfw==2.8.0
      - gtimer==1.0.0b5
      - gym==0.21.0
      - gym-notices==0.0.8
      - idna==3.10
      - imageio==2.36.1
      - jinja2==3.1.4
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - mujoco-py==2.1.2.14
      - networkx==3.4.2
      - numpy==2.2.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - pandas==2.2.3
      - pillow==11.0.0
      - pip==21.0
      - pycparser==2.22
      - pygame==2.6.1
      - pyglet==2.0.20
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - setuptools==65.5.0
      - six==1.17.0
      - sympy==1.13.1
      - torch==2.5.1
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - wheel==0.38.4

